services:
  misarmy_talkbot:
    image: misarmy_talkbot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - misarmy-talkbot-config:/home/bot/config
    env_file:
      - .env
    ports:
      - "5678:5678"

volumes:
  misarmy-talkbot-config:
